version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
